name: signal_strength_indicator
description: Customizable signal strength indicator widget for Flutter. Allows to easily visualize signal strength.
version: 0.3.0
author: Jan Štol <honzastol@gmail.com>
homepage: https://github.com/janstol/signal_strength_indicator

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
