name: Web demo deploy

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1.1.1
      with:
        channel: 'dev'
    
    - name: Enable web
      run: flutter config --enable-web
    
    - name: Add web support
      working-directory: example
      run: flutter create .
    
    - name: Get dependencies
      working-directory: example
      run: flutter pub get
    
    - name: Build
      working-directory: example
      run: flutter build web
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./example/build/web
